### ISSUE TITLE
Host sparkplug.eclipse.org on Eclipse Infrastructure

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/sparkplug.eclipse.org#1]
Similar to Host openadx.eclipse.org on Eclipse Infrastructure #12 EclipseFdn/openadx.eclipse.org#12, we would like to host this website on our cluster.

**Comment by chrisguindon** [comment]
@mbarbero I created a jenkins job for this website based off what we did for edgenative.eclipse.org:
https://foundation.eclipse.org/ci/webdev/job/sparkplug.eclipse.org/

I believe that @eclipsewebmaster created an entry for sparkplug.eclipse.org so we should be ready to move this to our cluster!

**Comment by chrisguindon** [comment]
webhook is also configured!

**Comment by chrisguindon** [comment]
@mbarbero You might want to hold off on this, Matt W. seems to be volunting himself to get this done!

**Comment by eclipsewebmaster** [comment]
I've run the deployment and re-run the build and sparkplug.eclipse.org is now live.
