### ISSUE TITLE
Add Part 2 video to the sparkplug resources page.

### ISSUE THREAD

**Issue by hassanjaber98** [EclipseFdn/sparkplug.eclipse.org#101]
link to video: https://www.youtube.com/watch?v=27_DKWjE3gg

link to page:https://sparkplug.eclipse.org/resources/

Title: Sparkplug Essentials 02 - Requirements for MQTT Sparkplug

Desc: What are the requirements for Sparkplug?

Sparkplug relies heavily on MQTT. In order to use Sparkplug it is important to use an MQTT broker that fully supports the MQTT 3.1.1 specification. It is not possible to use Sparkplug unless MQTT broker and clients support at least MQTT version 3.1.1 or higher.

The hard requirements for Sparkplug are

• QoS 0 and 1
• Retained Messages
• Last Will and Testament
• A flexible security system

Quality of Service 1 (delivery at most once) and Quality of Service 1 (delivery at least once) are mandatory for using Sparkplug. For more information about Quality of Service Levels read our blog post 
https://www.hivemq.com/blog/mqtt-esse...
or watch the video on the same topic: 
https://www.youtube.com/watch?v=hvhtJ...

Retained Messages and Last Will and Testament are also required features for MQTT Sparkplug. Make sure your MQTT broker offers 100% MQTT 3.1.1 conformity. For a better understanding of Retained Messages and Last Will and Testament we recommend reading our blog posts:

https://www.hivemq.com/blog/mqtt-esse...
https://www.hivemq.com/blog/mqtt-esse...

**Comment by linkfang** [comment]
Hi @hassanjaber98 , please preview the changes here:
https://deploy-preview-102--eclipsefdn-sparkplug.netlify.app/resources/

**Comment by hassanjaber98** [comment]
Thanks, looks good. Hassan JaberProduct Marketing Manager, IoT & Edge computing | Eclipse Foundationeclipse.org | Twitter | LinkedIn | YouTube Eclipse Foundation: The Community for Open Innovation and Collaboration From: Zhou (Link) FangSent: August 10, 2021 4:20 PMTo: EclipseFdn/sparkplug.eclipse.orgCc: Hassan Jaber; MentionSubject: Re: [EclipseFdn/sparkplug.eclipse.org] Add Part 2 video to the sparkplug resources page. (#101) Hi @hassanjaber98 , please preview the changes here:https://deploy-preview-102--eclipsefdn-sparkplug.netlify.app/resources/—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
