### ISSUE TITLE
Add video to the resources page of sparkplug

### ISSUE THREAD

**Issue by hassanjaber98** [EclipseFdn/sparkplug.eclipse.org#103]
Video link: https://www.youtube.com/watch?v=PPpdOUYolIY
Tittle: Sparkplug Essentials 04 - Sparkplug Key Principles
Desc: In this video, we introduce you to the eight key principles for MQTT Sparkplug:

1. Publish / Subscribe Architecture 
2. Report by Exception
3. Continuous Session Awareness
4. Death and Birth Certificates
5. Persistent Connections
6. Auto Discovery
7. Standardized Payload Definition
8. Standardized Topic Namespace

*** The Key Principles in Detail ***

1. Publish / Subscribe Architecture 
This displaces the old poll-response pattern, which had certain disadvantages. The modern decoupled publish-subscribe approach enables features like instant messaging and one-to-many communication

2. Report by Exception
Also based on a modern publish-subscribe pattern, Report-By-Exception saves a significant amount of bandwidth and computing power compared to the old poll-response pattern. The communication is also faster and more reliable since it uses push communication and does not need to wait for the next pull-response cycle when data or a device state changes.

3. Continuous Session Awareness
This is an important monitoring feature for online/offline states of devices. It provides a correct real-time view of the state of all devices, gateways, and applications in your deployment.

4. Death and Birth Certificates
This feature is used for the management and discovery of device states. As soon as an MQTT client goes online, it is required to send out a birth certificate. When it goes offline, the MQTT broker recognizes the changed state and informs every subscribed client by sending a death certificate.

5. Persistent Connections
All devices, gateways, and applications in a deployment use persistent TCP connections

6. Auto Discovery
Sparkplug provides Plug & Play interoperability. This is ensured by auto-discovery of device states, and what data will get sent.

7. Standardized Payload Definition
Defining a standard data format for all messages guarantees faultless communication between all participants.

8. Standardized Topic Namespace
This is also a requirement for Plug & Play interoperability. A common topic namespace used by all Sparkplug participants.

**Comment by linkfang** [comment]
Hi @hassanjaber98 ,
Please preview the changes here:
https://deploy-preview-106--eclipsefdn-sparkplug.netlify.app/resources/

**Comment by hassanjaber98** [comment]
Thanks looks good!
