### ISSUE TITLE
Add video to resources page of sparkplug

### ISSUE THREAD

**Issue by hassanjaber98** [EclipseFdn/sparkplug.eclipse.org#104]
Video link: https://www.youtube.com/watch?v=qhLYz0sITlw&t=22s
tittle: Sparkplug Essentials 05 - Sparkplug Components
Desc: In this video, we introduce you to the five infrastructure components of Sparkplug:

1. SCADA / IIoT Host
2. Edge of Network (EoN) Nodes
3. Devices / Sensors
4. MQTT Application Nodes
5. MQTT Broker

In detail:
1. SCADA / IIoT Host
It is also called Primary Application. The SCADA/IIoT Host is responsible for the supervision, monitoring, and control of all other components. It also provides state awareness for all participants in the deployment. Whenever a device or sensor becomes unavailable, the SCADA/IIoT Host will get this information. Unlike in a traditional system, the SCADA / IIoT Host is not connected to other components directly, but to the central MQTT broker. 

2. Edge of Network (EoN) Nodes
Edge of Network Nodes are sometimes also called gateways. Their function is to bridge devices and sensors, that are connected via protocols like OPC-UA, Modbus, or proprietary PLC vendor protocols, and cannot connect to the Sparkplug infrastructure directly. EoN Nodes also manage the state of connected sensors and devices.
 
3. Devices / Sensors
This is basically the industrial infrastructure on any manufacturing shop floor. Physical devices and sensors, that traditionally use a poll/response protocols for connectivity. EoN Nodes are used to bridge all the different communication protocols to Sparkplug and its typical MQTT publish/subscribe pattern. 

4. MQTT Application Nodes
Also known as Secondary Applications these are software systems like Manufacturing Executions Systems (MES), Historians, Analytics or even customized Applications, developed for individual use cases. MQTT Application Nodes usually consume data, but also send data back into the system.

5. MQTT Broker
This is the central data distribution component and is compulsory for every Sparkplug infrastructure. All EoN Nodes, MQTT Application Nodes, SCADA / IIoT Hosts, and Sparkplug enabled devices are connected to the MQTT broker. Usually, the MQTT broker is kept close to the devices. But for some deployments it can also be useful to establish a cloud-based MQTT broker. A free MQTT broker is for example HiveMQ Cloud, and there are also open-source brokers like HiveMQ CE, or Mosquitto available. For production environments, HiveMQ is recommended, since among other factors high availability and a proper permission system are key for business-critical use cases. Make sure to use a 100% MQTT compliant  broker. Cloud brokers like AWS IoT or Azure IoTHub will not work with Sparkplug, since they lack support of important MQTT features.

**Comment by linkfang** [comment]
Hi @hassanjaber98 ,
Please preview the changes here:
https://deploy-preview-105--eclipsefdn-sparkplug.netlify.app/resources/

Please note, the YouTube URL you offered is pointing to a specific time in the video (22 seconds), I removed the "&t=22s" in it so that it will be played from the beginning.

**Comment by hassanjaber98** [comment]
Sounds great, thanks!
