### ISSUE TITLE
Add video to the resources page

### ISSUE THREAD

**Issue by hassanjaber98** [EclipseFdn/sparkplug.eclipse.org#107]
Video link: https://www.youtube.com/watch?v=NKPb0FsM9bg
Tittle: Sparkplug: The Next Phase of Evolution For Industrial Automation | Virtual IoT Meetup
Desc: Digital transformation is changing the face of industrial automation. The proprietary, homogeneous and rigid architectures of yesterday are supplanted by ones that are open, heterogeneous and flexible. MQTT accelerated this transition 20 years ago. Sparkplug is now ready to do the same by making MQTT infrastructure interoperable out of the box. In this webinar, you will discover how Sparkplug can bring your digital transformation projects to the next level through three case studies.

**Comment by linkfang** [comment]
Hi @hassanjaber98 ,
Please preview the change here:
https://deploy-preview-108--eclipsefdn-sparkplug.netlify.app/resources/

**Comment by linkfang** [comment]
Hi @hassanjaber98 , just would like to confirm if we are good to push this live?

**Comment by hassanjaber98** [comment]
+1
