### ISSUE TITLE
Embed membership form on sparkplug.eclipse.org

### ISSUE THREAD

**Issue by shanda-eclipse** [EclipseFdn/sparkplug.eclipse.org#110]
Similar to [EclipseFdn/iot.eclipse.org#666](https://github.com/EclipseFdn/iot.eclipse.org/issues/666), we would like to embed the contact us form on sparkplug.eclipse.org. There is currently no link to a contact form on this site, but we will be creating a separate issue shortly to address the menu and will include the link to this new page. 

Here is the code to embed the form:
```
<!--[if lte IE 8]>
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2-legacy.js"></script>
<![endif]-->
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2.js"></script>
<script>
  hbspt.forms.create({
	region: "na1",
	portalId: "5413615",
	formId: "4f83381b-2fa0-499f-bae3-d8286072d360"
});
</script>
```
CC @hassanjaber98

**Comment by linkfang** [comment]
Hi @shanda-eclipse ,

Please preview the changes here, I added the form in "Join the Sparkplug Working Group" section
https://deploy-preview-111--eclipsefdn-sparkplug.netlify.app/join-us/

The Join Us button in top menu will take users to the new form:
https://deploy-preview-111--eclipsefdn-sparkplug.netlify.app/

**Comment by shanda-eclipse** [comment]
I would actually like the form to be on a new page. I have created a separate issue to address where we will link to the form: https://github.com/EclipseFdn/sparkplug.eclipse.org/issues/112

**Comment by linkfang** [comment]
The changes are live!

**Comment by shanda-eclipse** [comment]
I'm getting a 404 error on Membership > Our Members.

**Comment by linkfang** [comment]
> I'm getting a 404 error on Membership > Our Members.

I am surprised it did not show 404 on preview site, will do a quick fix on this.

**Comment by linkfang** [comment]
Please preview here:
https://deploy-preview-114--eclipsefdn-sparkplug.netlify.app/

This should also work on production site

**Comment by shanda-eclipse** [comment]
+1. Works on staging, so lets try it on prod.

**Comment by linkfang** [comment]
I tested on production, and it worked!
