### ISSUE TITLE
Join us form- Adding actual form to join us page

### ISSUE THREAD

**Issue by hassanjaber98** [EclipseFdn/sparkplug.eclipse.org#116]
webpage: https://sparkplug.eclipse.org/join-us/

We need to kindly add the actual join us form that we have here: https://sparkplug.eclipse.org/contact-join-us/ to the above join us part.

**Comment by linkfang** [comment]
Hi @hassanjaber98 , I added the form at the end of Join Us page and labeled that section as "Become a member", let me know if the position and the title work for you, thanks!

https://deploy-preview-117--eclipsefdn-sparkplug.netlify.app/join-us/#become-a-member

**Comment by hassanjaber98** [comment]
@linkfang Thanks, lets pls keep it at the top of the page to match other WG's also we want to stick to Join us.

Reference: https://iot.eclipse.org/membership/join-us/

**Comment by linkfang** [comment]
Sounds good!
Updated, please preview here:

https://deploy-preview-117--eclipsefdn-sparkplug.netlify.app/join-us/

**Comment by hassanjaber98** [comment]
looks good, thank you!

**Comment by linkfang** [comment]
NP! The change is now live!
