### ISSUE TITLE
Create initial look and feel for sparkplug.eclipse.org

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/sparkplug.eclipse.org#2]
The initial website will have 2 pages, the homepage and a FAQ page.

## Homepage content/section:
- Jumbotron
- News and Events
- Mission Statement
- Our Founding Members
- Testimonials
- FAQ teaser
- Featured footer for promoting mailing list.

## Typography
- @font-family-sans-serif: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;

## Color pallette: 
- @brand-primary: #396894; // Blue
- @brand-secondary: #5997BD; // Light Blue
- @brand-tertiary: #213970; // Dark Blue
- @brand-quaternary: #efefef; // Light Gray
- @brand-quinary: @brand-quaternary; // Light Gray (Breadcrumbs)
- @brand-info: @brand-tertiary;
- @brand-info-light: lighten(@brand-info, 20%);
- @brand-warning: @brand-primary;

- @brand-gradient: linear-gradient(-77deg, rgba(250,174,68,1) 0%, rgba(237,42,40,1) 50%, rgba(124,72,155,1) 100%);
- @brand-gradient-color: #faae44;

## Branding
- SVG Logo:
- Social media image: 
- Favicon:

**Comment by chrisguindon** [comment]
@ChristieWittEclipse  

The @brand-gradient and @brand-gradient-color are new and from edgenative website. We will want to define new color values for this site unless we want to use background images.

We also need to create graphics (branding): svg logo, social media image and favicons.

Finally, please let me know if we should use a different font!

**Comment by ChristieWittEclipse** [comment]
@chrisguindon 

The font choice is fine as is: @font-family-sans-serif: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;

Color pallette update:

@brand-primary: #1F769D; // Blue

@brand-secondary: #5997BD; // Light Blue

@brand-tertiary: #213970; // Dark Blue

@brand-quaternary: #efefef; // Light Gray

@brand-quinary: @brand-quaternary; // Light Gray (Breadcrumbs)

@brand-info: @brand-tertiary;

@brand-info-light: lighten(@brand-info, 20%);

@brand-warning: @brand-primary;

@brand-gradient: linear-gradient: No gradient

@brand-gradient-color: No gradient

Branding
SVG Logo, Social media image, and Favicon are attached.
[Web Assets Sparkplug.zip](https://github.com/EclipseFdn/sparkplug.eclipse.org/files/4073821/Web.Assets.Sparkplug.zip)

**Comment by chrisguindon** [comment]
Thanks @ChristieWittEclipse 

An alpha version of the site is now available via: https://eclipsefdn-sparkplug.netlify.com/

**Comment by ChristieWittEclipse** [comment]
Thanks @chrisguindon, please do a find/replace of the orange #FAAE44 and change it to #072B3F (Dark blue).

I'm not sure where that orange came from, I double checked the color pallet above. Once that is complete, let me know and I will discuss imagery with Thabang.

**Comment by chrisguindon** [comment]
As discussed with Christie, we will need to use a different color than #072B3F. 

She will update this bug after picking a new color for us to use.

**Comment by ChristieWittEclipse** [comment]
@chrisguindon please update the @brand-tertiary: #213970; // Dark Blue
to @brand-tertiary: #FD6C29; // Dark Orange

This color pallet looks nicer:
<img width="775" alt="Screen Shot 2020-01-20 at 3 48 45 PM" src="https://user-images.githubusercontent.com/58480647/72756852-875a4b00-3b9c-11ea-9d44-b5fd57ee026a.png">

**Comment by chrisguindon** [comment]
Color pallet is updated:
https://eclipsefdn-sparkplug.netlify.com/

**Comment by ChristieWittEclipse** [comment]
Thanks for updating @chrisguindon I've included updated background images below for the jumbotron section, mailing list section, mission statement, and testimonial section.

[sparkplug-website-images.zip](https://github.com/EclipseFdn/sparkplug.eclipse.org/files/4092096/sparkplug-website-images.zip)

**Comment by ChristieWittEclipse** [comment]
@chrisguindon here are the logos as discussed.
[Founding Member Logos.zip](https://github.com/EclipseFdn/sparkplug.eclipse.org/files/4124008/Founding.Member.Logos.zip)

**Comment by chrisguindon** [comment]
The initial look and feel is now live!

@ChristieWittEclipse, the mission background image was updated today and I expect to see it live in the next 15 minutes!

**Comment by ChristieWittEclipse** [comment]
@chrisguindon thanks! This is very minor, but if you could change the style on the mission statement image slightly, that would be great:
.featured-section-statement {
    background-size: cover;
    background-image: url(../images/mission-statement-image.jpg?2971690…);
    background-position: 0 **50%;**
}

**Comment by chrisguindon** [comment]
@ChristieWittEclipse Done! Closing this issue! Let's start opening new issues for changes moving forward! 

Thx all!
