### ISSUE TITLE
Update the event section on the SparkPlug website

### ISSUE THREAD

**Issue by Ioana240** [EclipseFdn/sparkplug.eclipse.org#22]
**Describe the bug**
Please update the events section on the SparkPlug website and link the event to this link: https://iot.eclipse.org/eclipse-iot-and-edge-day-san-jose-2020/.

Many thanks!
Ioana

**Comment by autumnfound** [comment]
Typically we post events with dates and expiration dates. Do we have a date for this yet?

**Comment by Ioana240** [comment]
Thank you for letting me know about the process, Martin. I didn't know this. I am checking with the team and will comment here shortly. 

Ioana

**Comment by Ioana240** [comment]
Hi everyone, 

In the course of today I will have the final dates for this event. I will post the dates in our chat here. Thank you!

-Ioana

**Comment by chrisguindon** [comment]
Closing this bug for lack of activity.

@Ioana240 please re-open this bug or create a new one once you have more info for us!
