### ISSUE TITLE
Image is a little bit distorted on IE11

### ISSUE THREAD

**Issue by flora8984461** [EclipseFdn/sparkplug.eclipse.org#38]
**Describe the bug**
Image is a little bit distorted on IE11

**Screenshots**
![image](https://user-images.githubusercontent.com/39588094/93637402-901d4e00-f9c3-11ea-976d-422f9ba5d56a.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] WIN10
 - Browser [e.g. chrome, safari] IE11

**Comment by chrisguindon** [comment]
Let's hold off for now since @ericpoirier is working on a re-design for the site.
