### ISSUE TITLE
Please add the Sparkplug Membership Prospectus to sparkplug.eclipse.org/

### ISSUE THREAD

**Issue by Ioana240** [EclipseFdn/sparkplug.eclipse.org#39]
Hi everyone,

Please add the Sparkplug Membership Prospectus on sparkplug.eclipse.org/.

1. Go to sparkplug.eclipse.org/
2. Go to the "Join" section
3. Replace the title "Contact us about your organization joining the Eclipse Foundation" with "Contact us about your organization joining the Sparkplug Working Group"
4. On the left side of the "Join" page, replace the old content with the content attached in the document: "Landing page “Sparkplug Membership Prospectus” "
5. Attach the sparkplug membership prospectus for download.

Thank you!
Ioana

[Landing page “Sparkplug Membership Prospectus”-Draft.docx](https://github.com/EclipseFdn/sparkplug.eclipse.org/files/5274996/Landing.page.Sparkplug.Membership.Prospectus.-Draft.docx)

[Sparkplug Membership Prospectus.pdf](https://github.com/EclipseFdn/sparkplug.eclipse.org/files/5274998/Sparkplug.Membership.Prospectus.pdf)

**Comment by ericpoirier** [comment]
Hi Ioana,

Can you provide the Hubspot form ID of the Sparkplug form?

Thanks.

**Comment by Ioana240** [comment]
Hi Eric, 

This is the HubSpot link: https://f.hubspotusercontent10.net/hubfs/5413615/Sparkplug%20Membership%20Prospectus.pdf

Thanks!

**Comment by Ioana240** [comment]
Hi Eric,

Please let me know if you need further details or information before setting the Prospectus live.

Thanks!
Ioana

**Comment by ericpoirier** [comment]
Me and Ioana had a conversation on Slack and we don't need a form ID for Sparkplug since it is currently using the default form. I will update the patch that I already created to use the default form ID.
