### ISSUE TITLE
Please add the Sparkplug membership prospectus in the banner section on sparkplug.eclipse.org

### ISSUE THREAD

**Issue by Ioana240** [EclipseFdn/sparkplug.eclipse.org#41]
The goal is to add the Sparkplug membership prospectus in the banner section on sparkplug.eclipse.org

1. Go to https://sparkplug.eclipse.org/
2. In the banner section, add a button on the right side similar to "Join us on Slack" button, see screenshot
3. Add the membership prospectus to the button, link here: https://www.eclipse.org/membership/documents/sparkplug-membership-prospectus.pdf

Thank you!
![2021 sparkplug](https://user-images.githubusercontent.com/61757816/95068317-6d01d680-0705-11eb-8596-4ca12b10a90e.PNG)

**Comment by chrisguindon** [comment]
@flora8984461 can you make sure this gets done today?

**Comment by flora8984461** [comment]
> @flora8984461 can you make sure this gets done today?

Sure.

**Comment by flora8984461** [comment]
Hello @Ioana240 @chrisguindon ,
Please check the preview https://deploy-preview-44--eclipsefdn-sparkplug.netlify.app/

Thanks!

**Comment by chrisguindon** [comment]
@Ioana240 @fdesbiens I am not convinced that "Membership Prospectus" is the right wording for the button but I defer to both of you on the content. Please let us know if we can merge this as-is.

**Comment by Ioana240** [comment]
@chrisguindon @flora8984461 @fdesbiens Thank you for the preview version! For the button, I would add "Download Membership Prospectus" instead of "Membership Prospectus". I still need to make a content change in the pdf document. I am updating the "new" pdf  in the course of this week. Thank you!

**Comment by flora8984461** [comment]
> @chrisguindon @flora8984461 @fdesbiens Thank you for the preview version! For the button, I would add "Download Membership Prospectus" instead of "Membership Prospectus". I still need to make a content change in the pdf document. I am updating the "new" pdf in the course of this week. Thank you!

@Ioana240 Hi Ioana, please feel free to reopen the issue when you finished the new PDF. Thx!

**Comment by Ioana240** [comment]
Hi @flora8984461, 

The new updated
[Uploading sparkplug-member-prospectus_-_version_Oct21.pdf…]()
 pdf of the Membership Prospectus is available now, new pdf is attached to the bug.

Hubspot ID link:  https://f.hubspotusercontent10.net/hubfs/5413615/sparkplug-member-prospectus%202020.pdf

Can you please replace the pdf/link:

1.  in the banner section on sparkplug.eclipse.org
2. on https://accounts.eclipse.org/contact/membership/sparkplug

Thank you!
Ioana

**Comment by chrisguindon** [comment]
Re-opening since @ericpoirier still needs to update accounts.eclipse.org.

**Comment by ericpoirier** [comment]
The "contact us" form has been updated with the most up to date PDF
https://accounts.eclipse.org/contact/membership/sparkplug

Let me know if there's anything else.

Thanks.

**Comment by Ioana240** [comment]
It looks good, thanks!

**Comment by ericpoirier** [comment]
Closing this issue since it was taken care of a few months ago.
