### ISSUE TITLE
Issues with the events list

### ISSUE THREAD

**Issue by fdesbiens** [EclipseFdn/sparkplug.eclipse.org#48]
All events currently on the Sparkplug home page are in the past. Yet, they are still displayed.

1. Why did they not vanish? Is there an issue with the expiration logic?

2. All URLs in these events point back to the sparkplug home page, not to the correct websites. Not sure if that is due to the previous point.

Thank you for your assistance!

**Comment by chrisguindon** [comment]
This was fixed a while back!
