### ISSUE TITLE
Please add the Sparkplug webinar on sparkplug.eclipse.org

### ISSUE THREAD

**Issue by Ioana240** [EclipseFdn/sparkplug.eclipse.org#50]
Hi everyone

Please add the Sparkplug webinar video on sparkplug.eclipse.org

We can create an (additional third) button titled "Watch our Sparkplug MQTT Webinar" in the header section and upload the YouTube video --> https://www.youtube.com/watch?v=PYYlEktoO-c&list=PLy7t4z5SYNaS3WoylJsNuox2f3t2gpQfK&index=1

When we have the new website with a resources section implemented, we would import the video on the new website as well.

@fdesbiens It would be great if you can share your input on this as well.

Thanks!
Ioana

**Comment by flora8984461** [comment]
Are we still waiting for inputs from @fdesbiens or we just add the third button in the header now?

**Comment by flora8984461** [comment]
Hi @Ioana240 , please check the preview: https://deploy-preview-54--eclipsefdn-sparkplug.netlify.app/
Thanks!

**Comment by Ioana240** [comment]
Hi @flora8984461, the preview looks good, thank you!

Ioana
