### ISSUE TITLE
Add a "Join Us" page

### ISSUE THREAD

**Issue by fdesbiens** [EclipseFdn/sparkplug.eclipse.org#55]
We missed one of the requirements for the new version of the Sparkplug website. The steering committee expected the "Join Us" button would lead to a dedicated page. 

The request is to add the page to the website. The copy for this new page can be found below.

=====
You can join the Sparkplug ecosystem in many different ways. The goal of this page is to explain you how.

#### Read the Sparkplug specification

The lastest published version of the specification is [available here](https://www.eclipse.org/tahu/spec/Sparkplug%20Topic%20Namespace%20and%20State%20ManagementV2.2-with%20appendix%20B%20format%20-%20Eclipse.pdf). 

If you are interested in the cutting edge, you can have a look at the [GitHub repository for the specification](https://github.com/eclipse/sparkplug). Anyone can propose changes to the specification by submitting pull requests. 

#### Join the [Sparkplug specification project](https://projects.eclipse.org/projects/iot.sparkplug)
You can become a contributor to the project by submitting a pull request. The process is explained on the home page for the repository.

If you make a number of contributions over time, the project team may invite you to join them and become a committer on the project. It is not necessary for your organization to be a member of the Eclipse Foundation or the Sparkplug working group in order for you to become a committer.

### Download an open source Sparkplug implementation
[Eclipse Tahu](https://projects.eclipse.org/projects/iot.tahu) is an open source commercial grade and production quality implementation of the Sparkplug specification. It is developed in sync with the specification itself.

### Join the Sparkplug Working Group
The Sparkplug working group is a group of like-minded companies and organizations that are driving the creation and stewardship of the Sparkplug specification and strengthening awareness and adoption through an open branding and compatibility program. 

Please have a look at our [membership prospectus](https://f.hubspotusercontent10.net/hubfs/5413615/sparkplug-member-prospectus%202020.pdf) to learn about the benefits of a Sparkplug membership.

The working group offers a mailing list and Slack workspace where members and non-members can exchange and collaborate.

#### Sparkplug Working Group Mailing List
You can join the mailing list by [following this link](https://accounts.eclipse.org/mailing-list/sparkplug-wg). Please note a free Eclipse Foundation account is required to subscribe.

#### Sparkplug Slack Workspace
[Click this link](Join me on Slack — it’s a faster, simpler way to work. Sign up here, from any device: https://join.slack.com/t/eclipse-sparkplug-wg/shared_invite/zt-btcn48au-luMXPXMbMhBzS4pCaLO6_w) to join the working group's Slack workspace. Many key Sparkplug contributors can be found there on a regular basis.

**Comment by ericpoirier** [comment]
Hi Frédéric,

I updated the PR that I created to update Sparkplug's design. The Join Us button now links to the join-us page.

https://deploy-preview-45--eclipsefdn-sparkplug.netlify.app/

Quick question. Should the link in the Jumbotron also link to the Join Us page or is it Ok for that button to link to Slack link it was previously requested.

Thanks.

**Comment by iskerrett** [comment]
Hi Eric

Thanks for adding the Join Us page.  Is it possible to make sure all of the Join Us buttons are linked to this page? Some still link to the slack channel.

Also will someone add some graphics to the Join Us page. It is pretty boring right now.

**Comment by croundy** [comment]
Thank you @fdesbiens for pulling this all together so quickly. The content looks quite solid, though to address the question from @iskerrett, it does need a little formatting help and perhaps some graphics. 

One thing that jumped out at me is the first sentence.    

Please replace: You can join the Sparkplug ecosystem in many different ways. The goal of this page is to explain you how.

With: You can join and contribute to the Sparkplug ecosystem in many ways:

**Comment by jbknepp** [comment]
A few things I noted.  

1. Top header quotation is currently cycling; should be static and use only Arlen's quote/headshot
2. Change 'ebook' to download of membership prospectus
3. Add popup or top section featuring the most recent Sparkplug webinar

**Comment by ericpoirier** [comment]
Hi @jbknepp,

The cycling of the testimonials was something that was requested here:
https://github.com/EclipseFdn/sparkplug.eclipse.org/issues/42#issuecomment-737287214

@Ioana240 are you ok with the decision to make it static content? I just want to make sure everyone is on the same page.

Thanks.

**Comment by ericpoirier** [comment]
> Hi Eric
> 
> Thanks for adding the Join Us page. Is it possible to make sure all of the Join Us buttons are linked to this page? Some still link to the slack channel.
> 
> Also will someone add some graphics to the Join Us page. It is pretty boring right now.

Hi @iskerrett !

I updated the Join Us link in the jumbotron, I believe that was the last link to update.

https://deploy-preview-45--eclipsefdn-sparkplug.netlify.app/

Let me know if there's anything else.

Thanks.

**Comment by fdesbiens** [comment]
@ericpoirier @Ioana240 About the testimonials: I double-checked my notes and the steering committee explicitly requested the testimonial to be Arlen Nipper's and static. Apologies for any confusion.

**Comment by fdesbiens** [comment]
@ericpoirier The "Join Us" page looks fine. Is it possible to have a bit more vertical spacing of the L1 (Maintain, Download, ...) and L2 sections?

**Comment by ericpoirier** [comment]
Hi @fdesbiens,

I updated the testimonials block to show only Arlen's testimonial.

I also updated the margin of the H2 and H3 to add more spacing. Note that this change is going to reflect on all sub-pages so that the spacing is consistant everywhere.

Let me know if there's anything else.

**Comment by iskerrett** [comment]
The Join Us page is looking a lot better.  There is one formating error. After the section 'Download an open source Sparkplug implementation' there should be another section header titled 'Join the Sparkplug Working Group'.  The text is actually already included in the paragraph about the Tahu download.

**Comment by ericpoirier** [comment]
Hi @iskerrett, 

I think I might have missed your last comment here.

You want the text to read as follow:

## Download an open source Sparkplug implementation

### Join the Sparkplug Working Group (new section header)

Eclipse Tahu is an open source commercial grade[...]



Thanks

**Comment by ericpoirier** [comment]
Hi @iskerrett,

A fix has been merged and will show up in a few minutes on production.
