### ISSUE TITLE
Add link to Sparkplug web page

### ISSUE THREAD

**Issue by iskerrett** [EclipseFdn/sparkplug.eclipse.org#56]
For the Sparkplug web site I would suggest in the section 'We need your help...' to add a link to the Sparkplug specification text. Here is the link to use https://www.eclipse.org/tahu/spec/Sparkplug%20Topic%20Namespace%20and%20State%20ManagementV2.2-with%20appendix%20B%20format%20-%20Eclipse.pdf

**Comment by chrisguindon** [comment]
Hi @iskerrett!

Just to confirm, the feedback is for the website re-design?
https://deploy-preview-45--eclipsefdn-sparkplug.netlify.app/

**Comment by ericpoirier** [comment]
@iskerrett I added a Specification button next to the Join Us button in the section you're talking about.

https://deploy-preview-45--eclipsefdn-sparkplug.netlify.app/

Let me know if there's something else to be updated.

Thanks.

**Comment by ericpoirier** [comment]
I'm going to close this issue since the redesign is now live on production.

Please reopen if there's an issue.

Thanks.
