### ISSUE TITLE
Header Quotations

### ISSUE THREAD

**Issue by jbknepp** [EclipseFdn/sparkplug.eclipse.org#57]
Header quotation is currently rotating.  This quotation should be fixed and use Arlen's headshot and quote.

**Comment by autumnfound** [comment]
Where is this happening? I checked the homepage and the testimonials are static there.

**Comment by ericpoirier** [comment]
@autumnfound This is a change to the redesign.

@jbknepp I updated the staging page to display only the one testimonial:
https://deploy-preview-45--eclipsefdn-sparkplug.netlify.app/?utm_source=github&utm_campaign=bot_dp

Let me know if there's anything else.

**Comment by ericpoirier** [comment]
This was updated and is now part of the redesign which is live on production.
