### ISSUE TITLE
Add Opto 22 as Members on Sparkplug WG

### ISSUE THREAD

**Issue by ZahraFazli** [EclipseFdn/sparkplug.eclipse.org#63]
Please add Opto 22 as Strategic Members on the Sparkplug WG
![logo_opto22_gradient_wtagline](https://user-images.githubusercontent.com/50374570/114083825-7834eb00-987d-11eb-92fe-5f1d50a65036.png)

Thanks!

**Comment by autumnfound** [comment]
Hey @ZahraFazli see https://deploy-preview-64--eclipsefdn-sparkplug.netlify.app/ for a preview of this change!
