### ISSUE TITLE
Add Flow Software as Participant Member 

### ISSUE THREAD

**Issue by ZahraFazli** [EclipseFdn/sparkplug.eclipse.org#67]
Hello,
Please add Flow Software as Participant Member on the Sparkplug working group website
![FLOW Logo - Final Green](https://user-images.githubusercontent.com/50374570/115894119-e99c9e00-a426-11eb-957f-f6aabc9440d6.png)
Thanks,
Zahra

**Comment by autumnfound** [comment]
I've created a patch for this, please see https://deploy-preview-68--eclipsefdn-sparkplug.netlify.app/#members for the preview!
