### ISSUE TITLE
Add white paper to sparkplug resources page 

### ISSUE THREAD

**Issue by hassanjaber98** [EclipseFdn/sparkplug.eclipse.org#71]
tittle: Intel & ExxonMobil joint public whitepaper on “Transform the Automation & Control of Onshore Oil &Gas Wells and Surface Facilities”. 

White paper link : https://www.intel.com/content/www/us/en/energy/resources/exxonmobil-transform-whitepaper.html

Desc: The Universal Wellpad Controller (UWC), developed in collaboration with ExxonMobil, Leverages Off-The-Shelf (OTS) hardware and opensource to provide an innovative solution that brings cost-effective, interoperable automation and control to onshore O&G operations.

pls add the above to the sparkplug resources page:
https://sparkplug.eclipse.org/resources/

**Comment by fdesbiens** [comment]
@chrisguindon Just attracting your attention on this one.

**Comment by autumnfound** [comment]
Preview is now available on https://deploy-preview-73--eclipsefdn-sparkplug.netlify.app/resources/, please let us know if there are any issues, otherwise it will be merged in in a few hours!

**Comment by hassanjaber98** [comment]
preview looks good, thank you
