### ISSUE TITLE
Tweaks to the members section of the website

### ISSUE THREAD

**Issue by fdesbiens** [EclipseFdn/sparkplug.eclipse.org#72]
Hi team.

I would like the following changes be made to the "members" section, please.

- Change the header from "Founding Members" to "Members"
- Remove ORing's logo (and remove their testimonial)
- Add Intel, SignalFire Telemetry and the University of Sheffield

@chrisguindon All of them provided their logos when they joined but let me know if you need assistance in securing some of those.

Thanks!

**Comment by autumnfound** [comment]
If you have png copies of those logos, it may be good to include them in cases like this! Sometimes companies prefer specific logos for certain cases, and it avoids confusion!

**Comment by linkfang** [comment]
Hi @fdesbiens ,

Please review the changes here:
https://deploy-preview-75--eclipsefdn-sparkplug.netlify.app/

Thanks

**Comment by fdesbiens** [comment]
Looking good, @linkfang! Thanks.

**Comment by linkfang** [comment]
Changes are now live:
https://sparkplug.eclipse.org/
