### ISSUE TITLE
Need to fix the link in the resources page/Sparkplug - MQTT Sparkplug Essentials Part 1 (link broken)

### ISSUE THREAD

**Issue by hassanjaber98** [EclipseFdn/sparkplug.eclipse.org#74]
Pls use the correct link below:
https://www.hivemq.com/blog/mqtt-sparkplug-essentials-part-1-introduction/

Desc: fix the link in the resources page of sparkplug
https://sparkplug.eclipse.org/resources/

**Comment by linkfang** [comment]
Hi @hassanjaber98 ,

The link has been fixed, please review here:
https://deploy-preview-76--eclipsefdn-sparkplug.netlify.app/resources/

**Comment by hassanjaber98** [comment]
Thank You, Hassan JaberProduct Marketing Manager, IoT & Edge computing | Eclipse Foundationeclipse.org | Twitter | LinkedIn | YouTube Eclipse Foundation: The Community for Open Innovation and Collaboration From: Zhou (Link) FangSent: May 20, 2021 10:26 AMTo: EclipseFdn/sparkplug.eclipse.orgCc: Hassan Jaber; MentionSubject: Re: [EclipseFdn/sparkplug.eclipse.org] Need to fix the link in the resources page/Sparkplug - MQTT Sparkplug Essentials Part 1 (link broken) (#74) Hi @hassanjaber98 ,The link has been fixed, please review here:https://deploy-preview-76--eclipsefdn-sparkplug.netlify.app/resources/—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by linkfang** [comment]
The fix is live:
https://sparkplug.eclipse.org/resources/
