### ISSUE TITLE
Add this video to the sparkplug resources page

### ISSUE THREAD

**Issue by hassanjaber98** [EclipseFdn/sparkplug.eclipse.org#77]
Desc: Digital Transformation Success Story: How Carrier Corp are leveraging MQTT Sparkplug for their Digital Transformation journey?
Video: Virtual webinar
link : https://inductiveautomation.wistia.com/medias/pepwmxn8jn

Sparkplug resources page: https://sparkplug.eclipse.org/resources/

**Comment by linkfang** [comment]
Hi @hassanjaber98 , please review the changes here:
https://deploy-preview-79--eclipsefdn-sparkplug.netlify.app/resources/

As the video is not from YouTube, so video thumbnail won't work properly, and as a result we have to use an image thumbnail for it.

**Comment by hassanjaber98** [comment]
Its ok for now, I’ve asked Inductive to provide their YouTube version if possible, once I receive it I’ll open another bug to replace. Hassan JaberProduct Marketing Manager, IoT & Edge computing | Eclipse Foundationeclipse.org | Twitter | LinkedIn | YouTube Eclipse Foundation: The Community for Open Innovation and Collaboration From: Zhou (Link) FangSent: May 21, 2021 11:39 AMTo: EclipseFdn/sparkplug.eclipse.orgCc: Hassan Jaber; MentionSubject: Re: [EclipseFdn/sparkplug.eclipse.org] Add this video to the sparkplug resources page (#77) Hi @hassanjaber98 , please review the changes here:https://deploy-preview-79--eclipsefdn-sparkplug.netlify.app/resources/As the video is not from YouTube, so video thumbnail won't work properly, and as a result we have to use an image thumbnail for it.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by linkfang** [comment]
> Its ok for now, I’ve asked Inductive to provide their YouTube version if possible, once I receive it I’ll open another bug to replace. 

OK, sounds good!
