### ISSUE TITLE
Add this news article to Articles section in the sparkplug resources page

### ISSUE THREAD

**Issue by hassanjaber98** [EclipseFdn/sparkplug.eclipse.org#78]
Desc:

Tittle: How to Connect a Smart Factory and Visualize IIoT Data with MQTT Sparkplug

Link: https://www.hivemq.com/blog/industry-4-0-part1-mqtt-sparkplug-iiot-smart-factory/?utm_content=167554418&utm_medium=social&utm_source=linkedin&hss_channel=lcp-2949784

sparkplug resources page: https://sparkplug.eclipse.org/resources/

**Comment by autumnfound** [comment]
@hassanjaber98 I've created a PR with this change visible on the following page: https://deploy-preview-80--eclipsefdn-sparkplug.netlify.app/resources/

One question, there is no description included. Would you like to add one?

**Comment by hassanjaber98** [comment]
Thanks for flagging it, though my self added desc to the bug request!Desc: In a smart factory and smart manufacturing ecosystem, Its worth explaining how to overcome the challenge of integrating and sharing data between heterogeneous systems and services ?  Hassan JaberProduct Marketing Manager, IoT & Edge computing | Eclipse Foundationeclipse.org | Twitter | LinkedIn | YouTube Eclipse Foundation: The Community for Open Innovation and Collaboration From: Martin LoweSent: May 25, 2021 10:24 AMTo: EclipseFdn/sparkplug.eclipse.orgCc: Hassan Jaber; MentionSubject: Re: [EclipseFdn/sparkplug.eclipse.org] Add this news article to Articles section in the sparkplug resources page ***@***.*** I've created a PR with this change visible on the following page: https://deploy-preview-80--eclipsefdn-sparkplug.netlify.app/resources/One question, there is no description included. Would you like to add one?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by autumnfound** [comment]
Added, thanks! Will be live soon

**Comment by hassanjaber98** [comment]
Thank you Hassan JaberProduct Marketing Manager, IoT & Edge computing | Eclipse Foundationeclipse.org | Twitter | LinkedIn | YouTube Eclipse Foundation: The Community for Open Innovation and Collaboration From: Martin LoweSent: May 25, 2021 10:46 AMTo: EclipseFdn/sparkplug.eclipse.orgCc: Hassan Jaber; MentionSubject: Re: [EclipseFdn/sparkplug.eclipse.org] Add this news article to Articles section in the sparkplug resources page (#78) Added, thanks! Will be live soon—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by autumnfound** [comment]
Closing as this was merged in
