### ISSUE TITLE
Sparkplug logo update to include the ® (registered) symbol 

### ISSUE THREAD

**Issue by ChristieWittEclipse** [EclipseFdn/sparkplug.eclipse.org#8]
Please update the first Sparkplug logo instance on the website (top left side) to include the ® (registered) symbol on https://sparkplug.eclipse.org/
I've attached the logo and Sharons approval email.
[sparkplug-update.zip](https://github.com/EclipseFdn/sparkplug.eclipse.org/files/4256888/sparkplug-update.zip)

**Comment by autumnfound** [comment]
Should I update the first usage of Sparkplug as a product on the home page to have the registered mark as well (mirroring some of our Jakarta.ee treatment)?

![image](https://user-images.githubusercontent.com/23018241/75366157-4684de80-588c-11ea-8810-1e5b5813da97.png)

**Comment by ChristieWittEclipse** [comment]
@autumnfound yes that would be great, to be consistent with how we're treating the Jakarta EE instance as well.

**Comment by autumnfound** [comment]
@ChristieWittEclipse the site has been updated, could you just do a quick check to make sure that encompasses everything you need from a legal/design standpoint?

**Comment by ChristieWittEclipse** [comment]
@autumnfound Looks great, thank you!
