### ISSUE TITLE
Pls add the below video to Eclipse IoT and Eclipse Sparkplug resources page 

### ISSUE THREAD

**Issue by hassanjaber98** [EclipseFdn/sparkplug.eclipse.org#81]
Desc: The use of open source in building IIoT solutions

Link to the video :https://www.youtube.com/watch?v=xtNWYuvUhWo
Eclipse IoT resources page: https://iot.eclipse.org/community/resources/
Eclipse sparkplug resources page:https://sparkplug.eclipse.org/resources/

Thank you,

**Comment by linkfang** [comment]
Now it's live!

**Comment by linkfang** [comment]
The changes are live!
