### ISSUE TITLE
The "View All Events" link is broken

### ISSUE THREAD

**Issue by fdesbiens** [EclipseFdn/sparkplug.eclipse.org#89]
![Capture d’écran 2021-06-15 103738](https://user-images.githubusercontent.com/5367020/122072609-bc84c000-cdc5-11eb-8781-bd60eee9f156.png)

The "View All Events" link on the Sparkplug home page leads to a 404 page. 

@chrisguindon I wonder if this is linked to the fact we are missing a "View More News" button as well. Filling a separate issue for that one.

Thank you in advance for fixing this!

**Comment by autumnfound** [comment]
@fdesbiens please see the following for a preview of the fix for this issue! https://deploy-preview-91--eclipsefdn-sparkplug.netlify.app/?utm_source=github&utm_campaign=bot_dp

This wasn't related to the mentioned issue, but is just something that wasn't caught until now.
