### ISSUE TITLE
Add a "View More News" Link to the Sparkplug home page

### ISSUE THREAD

**Issue by fdesbiens** [EclipseFdn/sparkplug.eclipse.org#90]
There is a list of recent news at the bottom of the Sparkplug home page. It displays the three most recent new items. However, the list is lacking a "View More News" button like the one found on iot.eclipse.org. 

![Capture d’écran 2021-06-15 104152](https://user-images.githubusercontent.com/5367020/122073320-551b4000-cdc6-11eb-91c9-49fde5029ca9.png)

@chrisguindon  I wonder if this is linked to issue  #89.

Thanks for your assistance!

**Comment by autumnfound** [comment]
@fdesbiens please see the following link for the fix for this issue! https://deploy-preview-92--eclipsefdn-sparkplug.netlify.app/ The black hover color is resolved by #91, it should inherit the same color used there!
