### ISSUE TITLE
Add this blog post to sparkplug resource page 

### ISSUE THREAD

**Issue by hassanjaber98** [EclipseFdn/sparkplug.eclipse.org#94]
blog link: https://www.hivemq.com/blog/how-5g-and-mqtt-accelerate-v2x-adaption/?utm_content=170171794&utm_medium=social&utm_source=linkedin&hss_channel=lcp-2949784

Desc: How 5G and MQTT Accelerate Vehicle-2-Everything (V2X) Adoption

sparkplug link : https://sparkplug.eclipse.org/resources/ (Articles section)

**Comment by autumnfound** [comment]
See https://deploy-preview-96--eclipsefdn-sparkplug.netlify.app/resources/ for preview of this article submission. I'll merge this once I get code review!
