### ISSUE TITLE
Add it to the video section in the sparkplug resources page

### ISSUE THREAD

**Issue by hassanjaber98** [EclipseFdn/sparkplug.eclipse.org#95]
Desc: Ignition Edge At The I/O Level
link:https://www.youtube.com/watch?v=OIS7nMBDnV0
Details: Opto 22 has taken the next step to connect you to the source of your operational data with an Ignition Edge-powered, Ethernet input/output (I/O) module named groov RIO.

**Comment by autumnfound** [comment]
See https://deploy-preview-97--eclipsefdn-sparkplug.netlify.app/resources/ for a preview of the video entry on the resources page. I'll be merging this once it has been reviewed!

**Comment by hassanjaber98** [comment]
> See https://deploy-preview-97--eclipsefdn-sparkplug.netlify.app/resources/ for a preview of the video entry on the resources page. I'll be merging this once it has been reviewed!

+1
